language: go
go:
  - 1.13
  - master
before_install:
  - go get github.com/mattn/goveralls
script: go test -v ./... -count=5 && go vet -v ./... && golint ./... && $GOPATH/bin/goveralls -service=travis-ci
